### ISSUE TITLE
Connection lost immediately when client tries to join server via Copy Link and Join

### ISSUE THREAD

**Issue by kubikaugustyn** [xzxADIxzx/Copy-Link-and-Join#4]
Hello, I’m trying to run the Copy Link and Join server and connect with a client, but every connection attempt results in immediate "connection lost: error" on the server logs.

I’m running the server via Docker with the correct port exposed, and the error occurs when trying to create a room in the client mod.
The server logs show connections accepted but instantly lost with no detailed error:

```log
[I] Connection 1 lost: error.
[I] Connection 2 lost: error.
[I] Connection 3 lost: error.
```

I verified:
- Server and client both use the latest version of Copy-Link-and-Join and Scheme Size respectively.
- Firewall and ports seem open and accessible.

My docker compose config:
```yaml
services:
  mindustry-claj:
    build: images/mindustry-claj
    container_name: mindustry-claj
    environment:
      - PORT=6568
    ports:
      - "6568:6568"
    tty: true
    stdin_open: true
    restart: unless-stopped
```
and Dockerfile:
```Dockerfile
FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && \
    git clone https://github.com/xzxADIxzx/Copy-Link-and-Join.git /app

RUN chmod +x ./gradlew
RUN ./gradlew jar

CMD ["sh", "-c", "java -jar /app/build/libs/app.jar ${PORT}"]
```

Could you advise what might cause this immediate connection drop?
Is there any additional debug info or logs I can provide?

Thank you!
